export const ROLE_MAP = {
  interests: {
    "Drones / UAVs": "Interest: Drones / UAVs",
    "Aerospace Systems": "Interest: Aerospace Systems",
    Robotics: "Interest: Robotics",
    "Embedded Systems": "Interest: Embedded Systems",
    "Hardware Hacking": "Interest: Hardware Hacking",
    "AI / Machine Learning": "Interest: AI / Machine Learning",
    "Computer Vision": "Interest: Computer Vision",
    "Data Science": "Interest: Data Science",
    Sustainability: "Interest: Sustainability",
    "Healthcare / MedTech": "Interest: Healthcare / MedTech",
    "Defense / Security": "Interest: Defense / Security",
    "Entrepreneurship / Startups": "Interest: Entrepreneurship / Startups",
    Other: "Interest: Other",
  },
  fields_of_study: {
    "Aerospace Engineering": "Field: Aerospace Engineering",
    "Mechanical Engineering": "Field: Mechanical Engineering",
    "Electrical Engineering": "Field: Electrical Engineering",
    "Computer Engineering": "Field: Computer Engineering",
    "Software Engineering": "Field: Software Engineering",
    "Computer Science": "Field: Computer Science",
    Physics: "Field: Physics",
    Mathematics: "Field: Mathematics",
    "Biology / Life Sciences": "Field: Biology / Life Sciences",
    "Business / Management": "Field: Business / Management",
    Economics: "Field: Economics",
    Other: "Field: Other",
  },
  level_of_study: {
    "Less than Secondary / High School": "Level: Pre-Secondary",
    "Secondary / High School": "Level: Secondary / High School",
    "Undergraduate University (2 year - community college or similar)": "Level: Undergraduate (2 year)",
    "Undergraduate University (3+ year)": "Level: Undergraduate (3+ year)",
    "Graduate University (Masters, Professional, Doctoral, etc)": "Level: Graduate",
    "Code School / Bootcamp": "Level: Code School / Bootcamp",
    "Other Vocational / Trade Program or Apprenticeship": "Level: Vocational / Trade",
    "Post Doctorate": "Level: Post Doctorate",
    "I’m not currently a student": "Level: Not Currently a Student",
    "Prefer not to answer": "Level: Prefer Not to Answer",
    Other: "Level: Other",
  },
  school: {
    "McGill University": "School: McGill University",
    "Concordia University": "School: Concordia University",
    "Université de Montréal": "School: Université de Montréal",
    "Polytechnique Montréal": "School: Polytechnique Montréal",
    "HEC Montréal": "School: HEC Montréal",
    UQAM: "School: UQAM",
    "ÉTS": "School: ÉTS",
    "Dawson College": "School: Dawson College",
    "John Abbott College": "School: John Abbott College",
    "Marianopolis College": "School: Marianopolis College",
    "Vanier College": "School: Vanier College",
    "Champlain College (St-Lambert)": "School: Champlain College (St-Lambert)",
    "Cégep du Vieux Montréal": "School: Cégep du Vieux Montréal",
    "Cégep de Maisonneuve": "School: Cégep de Maisonneuve",
    "Cégep André-Laurendeau": "School: Cégep André-Laurendeau",
    "Cégep Ahuntsic": "School: Cégep Ahuntsic",
    "Cégep Rosemont": "School: Cégep Rosemont",
    "Collège de Bois-de-Boulogne": "School: Collège de Bois-de-Boulogne",
    "Université Laval": "School: Université Laval",
    "Université de Sherbrooke": "School: Université de Sherbrooke",
    "Bishop’s University": "School: Bishop’s University",
    UQTR: "School: UQTR",
    UQO: "School: UQO",
  },
  team_mode: {
    free_agent: "Free Agent",
  },
} as const;

export type RoleMapCategory = keyof typeof ROLE_MAP;
